name: geodf
description: Geospatial timeseries analysis. Provides a GeoDataFrame object 
author: synw <ansterj@gmail.com>
homepage: https://github.com/synw/geodf
version: 0.0.1

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  pedantic: ^1.6.0
  geodesy: ^0.3.1
  ml_linalg: ^12.1.0
  console: ^3.1.0
  geopoint: ^0.5.0
  geojson: ^0.6.0
  duration: ^2.0.8
  units:
    git: git://github.com/yeradis/units.dart

dependency_overrides:
  geopoint: 
    path: ../geopoint

dev_dependencies:
  test: ^1.6.5
  test_coverage: ^0.3.0+1
